import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/componant/hello.jsx";
import logo from "../public/icons8-logo.gif"
import Ricky from "@/componant/easter";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
              <Image
                src={logo}
                alt="Notion Logo"
                width={50}
                height={50}
                priority
              />
          </div>
          {Navbar()}
        </div>

        <div className={styles.center}>
        <Ricky/>
        </div>
      </main>
    </>
  );
}
