import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/componant/hello.jsx";
import logo from "../public/icons8-logo.gif";
import photo from "../public/croix.png";
import { TemplateContext } from "next/dist/shared/lib/app-router-context.shared-runtime";
import Text_intr from "@/componant/text_intro";
 
const inter = Inter({ subsets: ["latin"] });
 
export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.description}>
        <div className={styles.logonavbar}>
          <Image className={styles.logonavbar} src={logo} alt="Notion Logo" width={60} height={60} priority />
        </div>
        {Navbar()}  
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.sectionPrincipal}>
          <div className={styles.sectionTexte}>
            <a>
              <h1 className={styles.titrePrincipal}>Hi!</h1>
              <h1 className={styles.titrePrincipal}>
                I'am <span className={styles.textecouleur}>Max</span>
              </h1>
              <h1 className={styles.titrePrincipal}>Web developer</h1>
              <button className={styles.contact_Button}>Contact</button>
            </a>
          </div>
          <div className={styles.sectionTexte}>
            <Image className={styles.logonavbar} src={photo} alt="photo" width={300} height={300} priority />
          </div>
        </div>
      </main>
    </>
  );
}